[package]
name = "forseti_ruleset_base"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "forseti_ruleset_base"
path = "src/main.rs"

[dependencies]
forseti_sdk = "*"
anyhow = "1.0"
serde_json = "1.0"
